### ISSUE TITLE
Otimizações

### ISSUE THREAD

**Issue by ricant95** [BazirM/pc#10]
- Permitir mover o avatar pressionando e segurando o botão de mover (e não a pressionar continuamente);

**Comment by MatosMarcos** [comment]
- Mostrar o level/score atual de ambos os jogadores na página de Ranking.

**Comment by MatosMarcos** [comment]
- Colocar botão logout na página de Ranking;

**Comment by MatosMarcos** [comment]
Apagar conta -> retirar o elemento dos maps level
