### ISSUE TITLE
17/05 - Patch 17/05

### ISSUE THREAD

**Issue by MatosMarcos** [BazirM/pc#9]
A ver:
Check collision entre criaturas vermelhas e avatares -> Perder jogo;
Check collision entre avatares e o limite do espaço -> Perder jogo;
Check collision entre criaturas verdes e avatares -> recarregar energia e desaparecer;
Propulsores;

Futuro:
Emparelhamento de jogadores a partir dos níveis;
Acrescentar vários rooms;
Pontuações.

**Comment by ricant95** [comment]
atualizado com a patch 19/05
